// <auto-generated />
using ApiKeyStorageService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiKeyStorageService.Migrations
{
    [DbContext(typeof(TornApiKeyContext))]
    [Migration("20201017235917_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiKeyStorageService.Model.TornApiKey", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<bool>("TrackCompany")
                        .HasColumnType("bit");

                    b.Property<bool>("TrackFaction")
                        .HasColumnType("bit");

                    b.Property<bool>("TrackPlayer")
                        .HasColumnType("bit");

                    b.Property<bool>("TrackTorn")
                        .HasColumnType("bit");

                    b.HasKey("PlayerId");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.ToTable("TornApiKey");
                });
#pragma warning restore 612, 618
        }
    }
}
